<?php
//identify this script/GUI
$localSys['scriptID']='gen_access1';
$localSys['scriptVersion']='4.0';
$localSys['componentID']='main';
$localSys['pageLevel']=1;

require('systeam/php/config.php');
require('resources/bais_00_includes.php');
require('systeam/php/auth_i2_v100.php');


exit('is this done? think so');

function convexp($n){
	$n=explode('E+0',$n);
	return $n[0] * pow(10,$n[1]);
}




$indexes[1]='Alaska';
$indexes[2]='Alaska';
$indexes[3]='Alaska';
$indexes[4]='Alaska';
$indexes[5]='Alaska';
$indexes[6]='Alaska';
$indexes[7]='Alaska';
$indexes[8]='Alaska';
$indexes[9]='Alaska';
$indexes[10]='Alaska';
$indexes[11]='Alaska';
$indexes[12]='Alaska';
$indexes[13]='Alaska';
$indexes[14]='Alaska';
$indexes[15]='Alaska';
$indexes[16]='Alaska';
$indexes[17]='Alaska';
$indexes[18]='Alaska';
$indexes[19]='Alaska';
$indexes[20]='Alaska';
$indexes[21]='Alaska';
$indexes[22]='Alaska';
$indexes[23]='Alaska';
$indexes[24]='Alaska';
$indexes[25]='Alaska';
$indexes[26]='Alaska';
$indexes[27]='Alaska';
$indexes[28]='Alaska';
$indexes[29]='Alaska';
$indexes[30]='Alaska';
$indexes[31]='Alaska';
$indexes[32]='Alaska';
$indexes[33]='Alaska';
$indexes[34]='Alaska';
$indexes[35]='Alaska';
$indexes[36]='Alaska';
$indexes[37]='Alaska';
$indexes[38]='Alaska';
$indexes[39]='Alaska';
$indexes[40]='Alaska';
$indexes[41]='Alaska';
$indexes[42]='Alaska';
$indexes[43]='Alaska';
$indexes[44]='Alaska';
$indexes[45]='Alaska';
$indexes[46]='Alaska';
$indexes[47]='Alaska';
$indexes[48]='Alaska';
$indexes[49]='Alaska';
$indexes[50]='Alaska';
$indexes[51]='Alaska';
$indexes[52]='Alaska';
$indexes[53]='Alaska';
$indexes[54]='Alaska';
$indexes[55]='Alaska';
$indexes[56]='Alaska';
$indexes[57]='Alaska';
$indexes[58]='Alaska';
$indexes[59]='Alaska';
$indexes[60]='Alaska';
$indexes[61]='Alaska';
$indexes[62]='Alaska';
$indexes[63]='Alaska';
$indexes[64]='Alaska';
$indexes[65]='Alaska';
$indexes[66]='Alaska';
$indexes[67]='Alaska';
$indexes[68]='Alaska';
$indexes[69]='Alaska';
$indexes[70]='Alaska';
$indexes[71]='Alaska';
$indexes[72]='Alaska';
$indexes[73]='Alaska';
$indexes[74]='Alaska';
$indexes[75]='Alaska';
$indexes[76]='Alaska';
$indexes[77]='Alaska';
$indexes[78]='Alaska';
$indexes[79]='Alaska';
$indexes[80]='Alaska';
$indexes[81]='Alaska';
$indexes[82]='Minnesota';
$indexes[83]='Washington';
$indexes[84]='Washington';
$indexes[85]='Montana';
$indexes[86]='Idaho';
$indexes[87]='North Dakota';
$indexes[88]='Washington';
$indexes[89]='Washington';
$indexes[90]='Washington';
$indexes[91]='Washington';
$indexes[92]='Washington';
$indexes[93]='Washington';
$indexes[94]='Washington';
$indexes[95]='Washington';
$indexes[96]='Michigan';
$indexes[97]='Washington';
$indexes[98]='Michigan';
$indexes[99]='Maine';
$indexes[100]='Wisconsin';
$indexes[101]='Wisconsin';
$indexes[102]='Wisconsin';
$indexes[103]='Wisconsin';
$indexes[104]='Oregon';
$indexes[105]='South Dakota';
$indexes[106]='Michigan';
$indexes[107]='Michigan';
$indexes[108]='Michigan';
$indexes[109]='Wisconsin';
$indexes[110]='New Hampshire';
$indexes[111]='Michigan';
$indexes[112]='Wisconsin';
$indexes[113]='Michigan';
$indexes[114]='Vermont';
$indexes[115]='New York';
$indexes[116]='Wyoming';
$indexes[117]='Maine';
$indexes[118]='Maine';
$indexes[119]='Maine';
$indexes[120]='Maine';
$indexes[121]='Maine';
$indexes[122]='Maine';
$indexes[123]='Maine';
$indexes[124]='Maine';
$indexes[125]='Maine';
$indexes[126]='Maine';
$indexes[127]='Maine';
$indexes[128]='Maine';
$indexes[129]='Maine';
$indexes[130]='Maine';
$indexes[131]='Maine';
$indexes[132]='Maine';
$indexes[133]='Maine';
$indexes[134]='Maine';
$indexes[135]='Maine';
$indexes[136]='Maine';
$indexes[137]='Maine';
$indexes[138]='Iowa';
$indexes[139]='Nebraska';
$indexes[140]='Massachusetts';
$indexes[141]='Illinois';
$indexes[142]='Pennsylvania';
$indexes[143]='Connecticut';
$indexes[144]='Rhode Island';
$indexes[145]='California';
$indexes[146]='Nevada';
$indexes[147]='Utah';
$indexes[148]='Ohio';
$indexes[149]='Indiana';
$indexes[150]='Ohio';
$indexes[151]='Ohio';
$indexes[152]='Rhode Island';
$indexes[153]='Ohio';
$indexes[154]='Rhode Island';
$indexes[155]='Rhode Island';
$indexes[156]='Ohio';
$indexes[157]='Massachusetts';
$indexes[158]='Rhode Island';
$indexes[159]='Rhode Island';
$indexes[160]='Massachusetts';
$indexes[161]='Massachusetts';
$indexes[162]='New Jersey';
$indexes[163]='New York';
$indexes[164]='Rhode Island';
$indexes[165]='New York';
$indexes[166]='Colorado';
$indexes[167]='New York';
$indexes[168]='New York';
$indexes[169]='New York';
$indexes[170]='New York';
$indexes[171]='West Virginia';
$indexes[172]='Missouri';
$indexes[173]='Kansas';
$indexes[174]='Delaware';
$indexes[175]='Maryland';
$indexes[176]='Delaware';
$indexes[177]='Delaware';
$indexes[178]='Virginia';
$indexes[179]='Kentucky';
$indexes[180]='District of Columbia';
$indexes[181]='Maryland';
$indexes[182]='Maryland';
$indexes[183]='Virginia';
$indexes[184]='Virginia';
$indexes[185]='California';
$indexes[186]='Virginia';
$indexes[187]='California';
$indexes[188]='California';
$indexes[189]='Arizona';
$indexes[190]='Oklahoma';
$indexes[191]='New Mexico';
$indexes[192]='Tennessee';
$indexes[193]='North Carolina';
$indexes[194]='Kentucky';
$indexes[195]='Texas';
$indexes[196]='Arkansas';
$indexes[197]='North Carolina';
$indexes[198]='North Carolina';
$indexes[199]='South Carolina';
$indexes[200]='Alabama';
$indexes[201]='Georgia';
$indexes[202]='Mississippi';
$indexes[203]='California';
$indexes[204]='California';
$indexes[205]='California';
$indexes[206]='California';
$indexes[207]='California';
$indexes[208]='California';
$indexes[209]='California';
$indexes[210]='Louisiana';
$indexes[211]='Florida';
$indexes[212]='Alabama';
$indexes[213]='Mississippi';
$indexes[214]='Mississippi';
$indexes[215]='Mississippi';
$indexes[216]='Mississippi';
$indexes[217]='Louisiana';
$indexes[218]='Florida';
$indexes[219]='Florida';
$indexes[220]='Hawaii';
$indexes[221]='Texas';
$indexes[222]='Florida';
$indexes[223]='Hawaii';
$indexes[224]='Hawaii';
$indexes[225]='Hawaii';
$indexes[226]='Hawaii';
$indexes[227]='Hawaii';
$indexes[228]='Hawaii';
$indexes[229]='Florida';
$indexes[230]='Hawaii';
$indexes[231]='Hawaii';
$indexes[232]='Florida';
$indexes[233]='Hawaii';
$indexes[234]='Florida';
$indexes[235]='Florida';
$indexes[236]='Florida';
$indexes[237]='Florida';
$indexes[238]='Florida';
$indexes[239]='Florida';
$indexes[240]='Florida';
$indexes[241]='Florida';
$indexes[242]='Hawaii';
$indexes[243]='Hawaii';
$indexes[244]='Hawaii';
$indexes[245]='Hawaii';
$indexes[246]='Hawaii';
$indexes[247]='Hawaii';
$indexes[248]='Hawaii';
$indexes[249]='Hawaii';
$indexes[250]='Hawaii';
$indexes[251]='Hawaii';
$indexes[252]='Hawaii';
$indexes[253]='Hawaii';
$indexes[254]='Hawaii';
$indexes[255]='Hawaii';
$indexes[256]='Hawaii';
$indexes[257]='Hawaii';
$indexes[258]='Hawaii';
$indexes[259]='Puerto Rico';
$indexes[260]='Puerto Rico';
$indexes[261]='Puerto Rico';
$indexes[262]='Puerto Rico';
$indexes[263]='Puerto Rico';
$indexes[264]='Puerto Rico';
$indexes[265]='Puerto Rico';
$indexes[266]='Puerto Rico';
$indexes[267]='Puerto Rico';
$indexes[268]='Puerto Rico';
$indexes[269]='Puerto Rico';
$indexes[270]='Puerto Rico';
$indexes[271]='Puerto Rico';
$indexes[272]='Puerto Rico';
$indexes[273]='Puerto Rico';

$a=file('st99_d00_pass2.txt');
foreach($a as $v){
	$v=trim($v,',');
	if(!trim($v) || $v=='END')continue;
	$v=explode(',',$v);
	if(count($v)==3){
		$index=$v[0];
		continue; //this is the centroid i believe
		$v[0]=$v[1];
		$v[1]=$v[2];
	}

	$i++;
	if(!fmod($i,50))echo '. ';
	if(($lng=convexp($v[0]))==0)continue;
	if(($lat=convexp($v[1]))==0)continue;
	$points[$indexes[$index]][$index].='{"lng":'.$lng.',"lat":'.$lat.'},';
}
foreach($points as $st_name=>$blocks){

	foreach($blocks as $n=>$v){
		$blocks[$n]='['.rtrim($v,',').']';
	}
	ob_start();
	q("ALTER TABLE aux_states ADD st_PointPerimeter2 LONGTEXT AFTER st_PointPerimeter", ERR_ECHO);
	$err=ob_get_contents();
	ob_end_clean();
	
	q("UPDATE aux_states SET st_PointPerimeter2='[".implode(',',$blocks)."]' WHERE st_name='$st_name'");
	continue;
	
	
	//-------------------------- old method one block only -------------------------------
	foreach($blocks as $n=>$v)$blocks[$n]=rtrim($v,',');
	prn($st_name);
	$str='['.implode(',',$blocks).']';
	
	q("UPDATE aux_states SET st_PointPerimeterIndex='".implode(',',array_keys($blocks))."', st_PointPerimeter='$str' WHERE st_name='$st_name'");
	//prn($qr,1);
}


?>